// lib/skills.data.mjs — curated tech-skill taxonomy (DATA ONLY; logic in skills.mjs).
//
// Precision-first, modeled on lib/languages.mjs: each skill has a canonical display
// name, lowercase alias surface forms, an ecosystem `family`, and `stackDefining`
// (true = a language/framework/runtime that defines a role's PRIMARY build stack;
// false = a cross-cutting tool shared across stacks — Docker, AWS, SQL, Git, CI/CD).
// Generated from a multi-agent sweep across software ecosystems, then hand-audited for
// alias precision. Edit freely; keep ambiguous English-word aliases in AMBIGUOUS (skills.mjs).

export const SKILLS = [
  { canonical: "Drupal", family: "cms", stackDefining: true, aliases: ["drupal"] },
  { canonical: "Joomla", family: "cms", stackDefining: true, aliases: ["joomla"] },
  { canonical: "Magento", family: "cms", stackDefining: true, aliases: ["magento","adobe commerce","magento 2"] },
  { canonical: "Shopify", family: "cms", stackDefining: true, aliases: ["shopify","liquid templating"] },
  { canonical: "WooCommerce", family: "cms", stackDefining: true, aliases: ["woocommerce","woo commerce"] },
  { canonical: "WordPress", family: "cms", stackDefining: true, aliases: ["wordpress","word press"] },
  { canonical: "Boost", family: "cpp", stackDefining: false, aliases: ["boost","boost c++","boost libraries"] },
  { canonical: "C", family: "cpp", stackDefining: true, aliases: ["c language","c programming","c lang","ansi c","c99","c11","c"] },
  { canonical: "C++", family: "cpp", stackDefining: true, aliases: ["c++","cpp","cplusplus","c plus plus","c++11","c++14","c++17","c++20","c++23","cpp11","cpp17"] },
  { canonical: "CMake", family: "cpp", stackDefining: false, aliases: ["cmake"] },
  { canonical: "Embedded C", family: "cpp", stackDefining: true, aliases: ["embedded c","embedded c++","embedded systems","embedded software","embedded development","firmware"] },
  { canonical: "OpenGL", family: "cpp", stackDefining: false, aliases: ["opengl","open gl","opengl es"] },
  { canonical: "POSIX", family: "cpp", stackDefining: false, aliases: ["posix","posix threads","pthreads"] },
  { canonical: "Qt", family: "cpp", stackDefining: true, aliases: ["qt","qt framework","qt5","qt6","qml","pyqt"] },
  { canonical: "RTOS", family: "cpp", stackDefining: false, aliases: ["rtos","freertos","real-time operating system","real time os"] },
  { canonical: "STL", family: "cpp", stackDefining: false, aliases: ["stl","standard template library","c++ stl"] },
  { canonical: "Unreal Engine", family: "cpp", stackDefining: true, aliases: ["unreal","unreal engine","ue4","ue5","unreal engine 4","unreal engine 5"] },
  { canonical: "Apache Airflow", family: "data-eng", stackDefining: false, aliases: ["apache airflow","airflow"] },
  { canonical: "Apache Flink", family: "data-eng", stackDefining: false, aliases: ["apache flink","flink"] },
  { canonical: "Apache Spark", family: "data-eng", stackDefining: false, aliases: ["apache spark","spark","pyspark","spark sql"] },
  { canonical: "Databricks", family: "data-eng", stackDefining: false, aliases: ["databricks"] },
  { canonical: "dbt", family: "data-eng", stackDefining: false, aliases: ["dbt","data build tool"] },
  { canonical: "ETL", family: "data-eng", stackDefining: false, aliases: ["etl","elt","etl/elt","extract transform load","data pipeline","data pipelines"] },
  { canonical: "Hadoop", family: "data-eng", stackDefining: false, aliases: ["hadoop","apache hadoop","hdfs","mapreduce"] },
  { canonical: "Snowflake", family: "data-eng", stackDefining: false, aliases: ["snowflake"] },
  { canonical: "Cassandra", family: "database", stackDefining: false, aliases: ["cassandra","apache cassandra"] },
  { canonical: "DynamoDB", family: "database", stackDefining: false, aliases: ["dynamodb","dynamo db","amazon dynamodb"] },
  { canonical: "Elasticsearch", family: "database", stackDefining: false, aliases: ["elasticsearch","elastic search","elk","elk stack"] },
  { canonical: "MongoDB", family: "database", stackDefining: false, aliases: ["mongodb","mongo db","mongo","mongoengine","pymongo"] },
  { canonical: "MySQL", family: "database", stackDefining: false, aliases: ["mysql","my sql","mariadb"] },
  { canonical: "Oracle Database", family: "database", stackDefining: false, aliases: ["oracle","oracle database","oracle db"] },
  { canonical: "PostgreSQL", family: "database", stackDefining: false, aliases: ["postgresql","postgres","psql","postgre sql"] },
  { canonical: "Redis", family: "database", stackDefining: false, aliases: ["redis"] },
  { canonical: "SQL", family: "database", stackDefining: false, aliases: ["sql","t-sql","tsql","pl/sql","plsql","ansi sql"] },
  { canonical: "SQL Server", family: "database", stackDefining: false, aliases: ["sql server","mssql","ms sql","microsoft sql server","sql server management studio","ssms"] },
  { canonical: "SQLite", family: "database", stackDefining: false, aliases: ["sqlite","sqlite3"] },
  { canonical: "T-SQL", family: "database", stackDefining: false, aliases: ["t-sql","tsql","transact-sql","transact sql"] },
  { canonical: "Ansible", family: "devops-cloud", stackDefining: false, aliases: ["ansible"] },
  { canonical: "AWS", family: "devops-cloud", stackDefining: false, aliases: ["aws","amazon web services","amazon aws"] },
  { canonical: "Azure", family: "devops-cloud", stackDefining: false, aliases: ["azure","microsoft azure","ms azure"] },
  { canonical: "Azure Functions", family: "devops-cloud", stackDefining: false, aliases: ["azure functions","azure function","azure function app","azure functions (.net)"] },
  { canonical: "CI/CD", family: "devops-cloud", stackDefining: false, aliases: ["ci/cd","ci cd","cicd","continuous integration","continuous delivery","continuous deployment"] },
  { canonical: "Docker", family: "devops-cloud", stackDefining: false, aliases: ["docker","dockerfile","docker-compose","docker compose","containerization"] },
  { canonical: "Git", family: "devops-cloud", stackDefining: false, aliases: ["git","github","gitlab","version control"] },
  { canonical: "GitHub Actions", family: "devops-cloud", stackDefining: false, aliases: ["github actions","gh actions"] },
  { canonical: "GitLab CI", family: "devops-cloud", stackDefining: false, aliases: ["gitlab ci","gitlab ci/cd","gitlab-ci","gitlab pipelines"] },
  { canonical: "Google Cloud Platform", family: "devops-cloud", stackDefining: false, aliases: ["gcp","google cloud","google cloud platform"] },
  { canonical: "Grafana", family: "devops-cloud", stackDefining: false, aliases: ["grafana"] },
  { canonical: "Helm", family: "devops-cloud", stackDefining: false, aliases: ["helm","helm charts"] },
  { canonical: "Jenkins", family: "devops-cloud", stackDefining: false, aliases: ["jenkins"] },
  { canonical: "Kubernetes", family: "devops-cloud", stackDefining: false, aliases: ["kubernetes","k8s","kubectl"] },
  { canonical: "Linux", family: "devops-cloud", stackDefining: false, aliases: ["linux","unix","ubuntu","bash scripting","centos","rhel","red hat enterprise linux","debian"] },
  { canonical: "Nginx", family: "devops-cloud", stackDefining: false, aliases: ["nginx"] },
  { canonical: "Prometheus", family: "devops-cloud", stackDefining: false, aliases: ["prometheus"] },
  { canonical: "Terraform", family: "devops-cloud", stackDefining: false, aliases: ["terraform"] },
  { canonical: ".NET", family: "dotnet", stackDefining: true, aliases: [".net","dotnet","dot net","microsoft .net",".net framework","dotnet framework"] },
  { canonical: ".NET 5+", family: "dotnet", stackDefining: true, aliases: [".net 5",".net 6",".net 7",".net 8",".net 9",".net5",".net6",".net7",".net8",".net9","net 6","net 8","dotnet 6","dotnet 8",".net 5+"] },
  { canonical: ".NET Core", family: "dotnet", stackDefining: true, aliases: [".net core","dotnet core",".netcore","net core"] },
  { canonical: "ADO.NET", family: "dotnet", stackDefining: false, aliases: ["ado.net","ado net","adonet"] },
  { canonical: "ASP.NET", family: "dotnet", stackDefining: true, aliases: ["asp.net","aspnet","asp net","asp.net mvc","aspnet mvc","asp.net web api","asp.net webforms","asp.net web forms"] },
  { canonical: "ASP.NET Core", family: "dotnet", stackDefining: true, aliases: ["asp.net core","aspnet core","aspnetcore","asp net core","asp.net core mvc","asp.net core web api","asp.net core minimal api"] },
  { canonical: "Blazor", family: "dotnet", stackDefining: true, aliases: ["blazor","blazor server","blazor webassembly","blazor wasm","blazor web app","asp.net blazor"] },
  { canonical: "C#", family: "dotnet", stackDefining: true, aliases: ["c#","csharp","c-sharp","c sharp","c#.net"] },
  { canonical: "Dapper", family: "dotnet", stackDefining: false, aliases: ["dapper","dapper.net","dapper orm"] },
  { canonical: "Entity Framework", family: "dotnet", stackDefining: false, aliases: ["entity framework","entityframework","ef6","entity framework 6"] },
  { canonical: "Entity Framework Core", family: "dotnet", stackDefining: false, aliases: ["entity framework core","ef core","efcore","entityframework core","entity framework core (ef core)"] },
  { canonical: "F#", family: "dotnet", stackDefining: true, aliases: ["f#","fsharp","f-sharp","f sharp"] },
  { canonical: "LINQ", family: "dotnet", stackDefining: false, aliases: ["linq","language integrated query","linq to sql","linq to entities","linq to objects"] },
  { canonical: "ML.NET", family: "dotnet", stackDefining: false, aliases: ["ml.net","ml net","mlnet"] },
  { canonical: "NuGet", family: "dotnet", stackDefining: false, aliases: ["nuget","nuget package","nuget packages","nuget package manager"] },
  { canonical: "Razor Pages", family: "dotnet", stackDefining: false, aliases: ["razor pages","razor","razor views",".cshtml","razor page"] },
  { canonical: "SignalR", family: "dotnet", stackDefining: false, aliases: ["signalr","asp.net signalr","aspnet signalr","azure signalr"] },
  { canonical: "VB.NET", family: "dotnet", stackDefining: true, aliases: ["vb.net","vb .net","vbnet","visual basic .net","visual basic.net","visual basic .net (vb.net)"] },
  { canonical: "WCF", family: "dotnet", stackDefining: false, aliases: ["wcf","windows communication foundation"] },
  { canonical: "WinForms", family: "dotnet", stackDefining: true, aliases: ["winforms","win forms","windows forms","windows forms (winforms)","system.windows.forms"] },
  { canonical: "WPF", family: "dotnet", stackDefining: true, aliases: ["wpf","windows presentation foundation"] },
  { canonical: "REST API", family: "generic", stackDefining: false, aliases: ["rest","rest api","restful","restful api","restful apis"] },
  { canonical: "Visual Studio", family: "generic", stackDefining: false, aliases: ["visual studio","ms visual studio","microsoft visual studio","vs ide"] },
  { canonical: "Chi", family: "golang", stackDefining: true, aliases: ["go-chi","chi router","chi"] },
  { canonical: "Cobra", family: "golang", stackDefining: false, aliases: ["cobra cli","spf13/cobra","cobra"] },
  { canonical: "Echo", family: "golang", stackDefining: true, aliases: ["echo framework","labstack echo","echo"] },
  { canonical: "Fiber", family: "golang", stackDefining: true, aliases: ["gofiber","go fiber","fiber framework","fiber"] },
  { canonical: "Gin", family: "golang", stackDefining: true, aliases: ["gin gonic","gin-gonic","gin framework","gin"] },
  { canonical: "Go", family: "golang", stackDefining: true, aliases: ["golang","go lang","go programming","go"] },
  { canonical: "GORM", family: "golang", stackDefining: false, aliases: ["gorm"] },
  { canonical: "gRPC", family: "golang", stackDefining: false, aliases: ["grpc","grpc-go"] },
  { canonical: "Akka", family: "java-jvm", stackDefining: true, aliases: ["akka","akka actors","akka streams"] },
  { canonical: "Ant", family: "java-jvm", stackDefining: false, aliases: ["apache ant","ant"] },
  { canonical: "Apache CXF", family: "java-jvm", stackDefining: false, aliases: ["apache cxf","cxf"] },
  { canonical: "Apache Struts", family: "java-jvm", stackDefining: true, aliases: ["struts","apache struts","struts2"] },
  { canonical: "Clojure", family: "java-jvm", stackDefining: true, aliases: ["clojure"] },
  { canonical: "Dropwizard", family: "java-jvm", stackDefining: true, aliases: ["dropwizard"] },
  { canonical: "GlassFish", family: "java-jvm", stackDefining: false, aliases: ["glassfish"] },
  { canonical: "Gradle", family: "java-jvm", stackDefining: false, aliases: ["gradle"] },
  { canonical: "Groovy", family: "java-jvm", stackDefining: true, aliases: ["groovy","apache groovy"] },
  { canonical: "Hazelcast", family: "java-jvm", stackDefining: false, aliases: ["hazelcast"] },
  { canonical: "Hibernate", family: "java-jvm", stackDefining: true, aliases: ["hibernate","hibernate orm"] },
  { canonical: "Java", family: "java-jvm", stackDefining: true, aliases: ["java","core java","java se","java ee","j2ee","jakarta ee","java 8","java 11","java 17","java 21"] },
  { canonical: "Java EE / Jakarta EE", family: "java-jvm", stackDefining: true, aliases: ["java ee","jakarta ee","ejb","enterprise java beans","cdi","java ee / jakarta ee"] },
  { canonical: "JavaServer Faces", family: "java-jvm", stackDefining: false, aliases: ["jsf","javaserver faces","java server faces"] },
  { canonical: "JAX-RS", family: "java-jvm", stackDefining: false, aliases: ["jax-rs","jaxrs","jakarta restful web services"] },
  { canonical: "Jersey", family: "java-jvm", stackDefining: false, aliases: ["jersey","jersey framework"] },
  { canonical: "Jetty", family: "java-jvm", stackDefining: false, aliases: ["jetty","eclipse jetty"] },
  { canonical: "JPA", family: "java-jvm", stackDefining: false, aliases: ["jpa","java persistence api","jakarta persistence"] },
  { canonical: "JSP", family: "java-jvm", stackDefining: false, aliases: ["jsp","javaserver pages","java server pages"] },
  { canonical: "Kotlin", family: "java-jvm", stackDefining: true, aliases: ["kotlin","kotlin lang"] },
  { canonical: "Log4j", family: "java-jvm", stackDefining: false, aliases: ["log4j","log4j2","apache log4j"] },
  { canonical: "Lombok", family: "java-jvm", stackDefining: false, aliases: ["lombok","project lombok"] },
  { canonical: "Maven", family: "java-jvm", stackDefining: false, aliases: ["maven","apache maven","mvn"] },
  { canonical: "Micronaut", family: "java-jvm", stackDefining: true, aliases: ["micronaut"] },
  { canonical: "MyBatis", family: "java-jvm", stackDefining: false, aliases: ["mybatis","ibatis"] },
  { canonical: "Netty", family: "java-jvm", stackDefining: false, aliases: ["netty"] },
  { canonical: "Play Framework", family: "java-jvm", stackDefining: true, aliases: ["play framework","play2","playframework"] },
  { canonical: "Quarkus", family: "java-jvm", stackDefining: true, aliases: ["quarkus"] },
  { canonical: "sbt", family: "java-jvm", stackDefining: false, aliases: ["sbt","scala build tool"] },
  { canonical: "Scala", family: "java-jvm", stackDefining: true, aliases: ["scala"] },
  { canonical: "Servlets", family: "java-jvm", stackDefining: false, aliases: ["servlets","java servlets","servlet api"] },
  { canonical: "SLF4J", family: "java-jvm", stackDefining: false, aliases: ["slf4j"] },
  { canonical: "Spring", family: "java-jvm", stackDefining: true, aliases: ["spring","spring framework"] },
  { canonical: "Spring Batch", family: "java-jvm", stackDefining: false, aliases: ["spring batch","spring-batch"] },
  { canonical: "Spring Boot", family: "java-jvm", stackDefining: true, aliases: ["spring boot","springboot","spring-boot"] },
  { canonical: "Spring Cloud", family: "java-jvm", stackDefining: false, aliases: ["spring cloud","spring-cloud"] },
  { canonical: "Spring Data", family: "java-jvm", stackDefining: false, aliases: ["spring data","spring-data","spring data jpa"] },
  { canonical: "Spring Integration", family: "java-jvm", stackDefining: false, aliases: ["spring integration","spring-integration"] },
  { canonical: "Spring MVC", family: "java-jvm", stackDefining: false, aliases: ["spring mvc","springmvc","spring web mvc"] },
  { canonical: "Spring Security", family: "java-jvm", stackDefining: false, aliases: ["spring security","spring-security"] },
  { canonical: "Spring WebFlux", family: "java-jvm", stackDefining: false, aliases: ["spring webflux","webflux","spring reactive"] },
  { canonical: "Tomcat", family: "java-jvm", stackDefining: false, aliases: ["tomcat","apache tomcat"] },
  { canonical: "Vert.x", family: "java-jvm", stackDefining: true, aliases: ["vert.x","vertx","eclipse vert.x"] },
  { canonical: "WebLogic", family: "java-jvm", stackDefining: false, aliases: ["weblogic","oracle weblogic"] },
  { canonical: "WebSphere", family: "java-jvm", stackDefining: false, aliases: ["websphere","ibm websphere"] },
  { canonical: "WildFly", family: "java-jvm", stackDefining: false, aliases: ["wildfly","jboss","jboss eap"] },
  { canonical: "Bun", family: "js-backend", stackDefining: true, aliases: ["bun","bun.js","bunjs"] },
  { canonical: "Deno", family: "js-backend", stackDefining: true, aliases: ["deno"] },
  { canonical: "Express", family: "js-backend", stackDefining: true, aliases: ["express","express.js","expressjs","express js"] },
  { canonical: "Fastify", family: "js-backend", stackDefining: true, aliases: ["fastify"] },
  { canonical: "Hapi", family: "js-backend", stackDefining: true, aliases: ["hapi","hapi.js","hapijs","hapi js","@hapi"] },
  { canonical: "Koa", family: "js-backend", stackDefining: true, aliases: ["koa","koa.js","koajs","koa js"] },
  { canonical: "NestJS", family: "js-backend", stackDefining: true, aliases: ["nestjs","nest.js","nest js"] },
  { canonical: "Node.js", family: "js-backend", stackDefining: true, aliases: ["node.js","nodejs","node js","node"] },
  { canonical: "Socket.IO", family: "js-backend", stackDefining: false, aliases: ["socket.io","socketio","socket io","socket.io.js"] },
  { canonical: "Accessibility (WCAG/ARIA)", family: "js-frontend", stackDefining: false, aliases: ["accessibility","wcag","aria","a11y","web accessibility","accessibility (wcag/aria)"] },
  { canonical: "Alpine.js", family: "js-frontend", stackDefining: false, aliases: ["alpine.js","alpinejs","alpine js"] },
  { canonical: "Angular", family: "js-frontend", stackDefining: true, aliases: ["angular","angularjs","angular.js","angular js","angular 2+"] },
  { canonical: "Ant Design", family: "js-frontend", stackDefining: false, aliases: ["ant design","antd","ant-design"] },
  { canonical: "Astro", family: "js-frontend", stackDefining: true, aliases: ["astro","astro.js","astrojs"] },
  { canonical: "Babel", family: "js-frontend", stackDefining: false, aliases: ["babel","babeljs","babel.js"] },
  { canonical: "Backbone.js", family: "js-frontend", stackDefining: true, aliases: ["backbone","backbone.js","backbonejs","backbone js"] },
  { canonical: "Bootstrap", family: "js-frontend", stackDefining: false, aliases: ["bootstrap","bootstrap 5","twitter bootstrap"] },
  { canonical: "Chakra UI", family: "js-frontend", stackDefining: false, aliases: ["chakra ui","chakra-ui","chakraui"] },
  { canonical: "CSS", family: "js-frontend", stackDefining: false, aliases: ["css","css3","css 3"] },
  { canonical: "D3.js", family: "js-frontend", stackDefining: false, aliases: ["d3.js","d3js","d3 js"] },
  { canonical: "Ember.js", family: "js-frontend", stackDefining: true, aliases: ["ember","ember.js","emberjs","ember js"] },
  { canonical: "esbuild", family: "js-frontend", stackDefining: false, aliases: ["esbuild","es build"] },
  { canonical: "Gatsby", family: "js-frontend", stackDefining: true, aliases: ["gatsby","gatsby.js","gatsbyjs"] },
  { canonical: "GraphQL", family: "js-frontend", stackDefining: false, aliases: ["graphql","graph ql","apollo client","apollo-client"] },
  { canonical: "HTML", family: "js-frontend", stackDefining: false, aliases: ["html","html5","html 5"] },
  { canonical: "JavaScript", family: "js-frontend", stackDefining: true, aliases: ["javascript","java script","ecmascript","es6","es2015","es2020","vanilla js","vanilla javascript"] },
  { canonical: "jQuery", family: "js-frontend", stackDefining: false, aliases: ["jquery","jquery.js"] },
  { canonical: "Less", family: "js-frontend", stackDefining: false, aliases: ["less","less css","lesscss"] },
  { canonical: "Material UI", family: "js-frontend", stackDefining: false, aliases: ["material ui","material-ui","materialui","mui","material design"] },
  { canonical: "MobX", family: "js-frontend", stackDefining: false, aliases: ["mobx","mob x"] },
  { canonical: "Next.js", family: "js-frontend", stackDefining: true, aliases: ["next.js","nextjs","next js"] },
  { canonical: "NgRx", family: "js-frontend", stackDefining: false, aliases: ["ngrx","ng rx"] },
  { canonical: "Nuxt", family: "js-frontend", stackDefining: true, aliases: ["nuxt","nuxt.js","nuxtjs","nuxt js"] },
  { canonical: "Preact", family: "js-frontend", stackDefining: true, aliases: ["preact","preact.js","preactjs"] },
  { canonical: "Progressive Web Apps", family: "js-frontend", stackDefining: false, aliases: ["progressive web app","progressive web apps","pwa","service worker","service workers"] },
  { canonical: "Qwik", family: "js-frontend", stackDefining: true, aliases: ["qwik","qwik.js","qwikjs"] },
  { canonical: "React", family: "js-frontend", stackDefining: true, aliases: ["react","react.js","reactjs","react js"] },
  { canonical: "React Query", family: "js-frontend", stackDefining: false, aliases: ["react query","react-query","tanstack query","tanstack-query"] },
  { canonical: "Redux", family: "js-frontend", stackDefining: false, aliases: ["redux","redux toolkit","redux-toolkit","react-redux"] },
  { canonical: "Remix", family: "js-frontend", stackDefining: true, aliases: ["remix","remix.run","remix run"] },
  { canonical: "Responsive Design", family: "js-frontend", stackDefining: false, aliases: ["responsive design","responsive web design","responsive layout","mobile-first","mobile first"] },
  { canonical: "Rollup", family: "js-frontend", stackDefining: false, aliases: ["rollup","rollup.js","rollupjs"] },
  { canonical: "RxJS", family: "js-frontend", stackDefining: false, aliases: ["rxjs","rx.js","reactive extensions"] },
  { canonical: "Sass", family: "js-frontend", stackDefining: false, aliases: ["sass","scss","sass/scss"] },
  { canonical: "SolidJS", family: "js-frontend", stackDefining: true, aliases: ["solidjs","solid.js","solid js"] },
  { canonical: "Stencil", family: "js-frontend", stackDefining: false, aliases: ["stencil","stenciljs","stencil.js"] },
  { canonical: "Storybook", family: "js-frontend", stackDefining: false, aliases: ["storybook","storybook.js"] },
  { canonical: "Styled Components", family: "js-frontend", stackDefining: false, aliases: ["styled components","styled-components","styledcomponents"] },
  { canonical: "Svelte", family: "js-frontend", stackDefining: true, aliases: ["svelte","sveltejs","svelte.js"] },
  { canonical: "SvelteKit", family: "js-frontend", stackDefining: true, aliases: ["sveltekit","svelte kit"] },
  { canonical: "Tailwind CSS", family: "js-frontend", stackDefining: false, aliases: ["tailwind","tailwind css","tailwindcss"] },
  { canonical: "Three.js", family: "js-frontend", stackDefining: false, aliases: ["three.js","threejs","three js"] },
  { canonical: "TypeScript", family: "js-frontend", stackDefining: true, aliases: ["typescript","type script","type-script"] },
  { canonical: "Vite", family: "js-frontend", stackDefining: false, aliases: ["vite","vitejs","vite.js"] },
  { canonical: "Vue.js", family: "js-frontend", stackDefining: true, aliases: ["vue","vue.js","vuejs","vue js","vue 3"] },
  { canonical: "Web Components", family: "js-frontend", stackDefining: false, aliases: ["web components","web-components","custom elements","lit","lit-element","lit-html"] },
  { canonical: "WebAssembly", family: "js-frontend", stackDefining: false, aliases: ["webassembly","wasm","web assembly"] },
  { canonical: "Webpack", family: "js-frontend", stackDefining: false, aliases: ["webpack","web pack"] },
  { canonical: "Webpack Dev Server", family: "js-frontend", stackDefining: false, aliases: ["webpack dev server","webpack-dev-server"] },
  { canonical: "Webpack Module Federation", family: "js-frontend", stackDefining: false, aliases: ["module federation","micro frontends","micro-frontends","microfrontends","webpack module federation"] },
  { canonical: "Webpack/PostCSS", family: "js-frontend", stackDefining: false, aliases: ["postcss","post css","webpack/postcss"] },
  { canonical: "Zustand", family: "js-frontend", stackDefining: false, aliases: ["zustand"] },
  { canonical: "Apache Kafka", family: "messaging", stackDefining: false, aliases: ["kafka","apache kafka"] },
  { canonical: "RabbitMQ", family: "messaging", stackDefining: false, aliases: ["rabbitmq","rabbit mq","amqp"] },
  { canonical: "REST", family: "messaging", stackDefining: false, aliases: ["rest","rest api","restful","restful api","rest apis","restful apis"] },
  { canonical: ".NET MAUI", family: "mobile", stackDefining: true, aliases: [".net maui","net maui","maui",".net multi-platform app ui","dotnet maui","microsoft maui"] },
  { canonical: "Android", family: "mobile", stackDefining: true, aliases: ["android","android development","android developer","android app","android sdk"] },
  { canonical: "Android Jetpack", family: "mobile", stackDefining: false, aliases: ["android jetpack","jetpack","androidx"] },
  { canonical: "Android SDK", family: "mobile", stackDefining: true, aliases: ["android sdk","android development","android (java)","android"] },
  { canonical: "Android Studio", family: "mobile", stackDefining: false, aliases: ["android studio"] },
  { canonical: "Apache Cordova", family: "mobile", stackDefining: true, aliases: ["cordova","apache cordova","phonegap"] },
  { canonical: "App Store Connect", family: "mobile", stackDefining: false, aliases: ["app store connect","appstore connect","testflight"] },
  { canonical: "ARCore", family: "mobile", stackDefining: false, aliases: ["arcore","ar core"] },
  { canonical: "ARKit", family: "mobile", stackDefining: false, aliases: ["arkit","ar kit"] },
  { canonical: "Capacitor", family: "mobile", stackDefining: false, aliases: ["capacitor","capacitorjs","capacitor js"] },
  { canonical: "Cocoa Touch", family: "mobile", stackDefining: false, aliases: ["cocoa touch","cocoatouch","cocoa"] },
  { canonical: "Combine", family: "mobile", stackDefining: false, aliases: ["combine framework","apple combine","combine"] },
  { canonical: "Core Data", family: "mobile", stackDefining: false, aliases: ["core data","coredata"] },
  { canonical: "Dart", family: "mobile", stackDefining: true, aliases: ["dart","dart language","dart lang"] },
  { canonical: "Expo", family: "mobile", stackDefining: false, aliases: ["expo","expo go"] },
  { canonical: "Firebase", family: "mobile", stackDefining: false, aliases: ["firebase","firebase cloud messaging","firestore","fcm"] },
  { canonical: "Flutter", family: "mobile", stackDefining: true, aliases: ["flutter","flutter sdk"] },
  { canonical: "Google Play", family: "mobile", stackDefining: false, aliases: ["google play","play store","google play console"] },
  { canonical: "Ionic", family: "mobile", stackDefining: true, aliases: ["ionic","ionic framework"] },
  { canonical: "iOS", family: "mobile", stackDefining: true, aliases: ["ios","ios development","ios developer","ios app","ipados"] },
  { canonical: "Java (Android)", family: "mobile", stackDefining: false, aliases: ["android java","java (android)"] },
  { canonical: "Jetpack Compose", family: "mobile", stackDefining: true, aliases: ["jetpack compose","compose android","jetpack-compose","compose multiplatform"] },
  { canonical: "Kotlin Multiplatform", family: "mobile", stackDefining: true, aliases: ["kotlin multiplatform","kmp","kotlin multiplatform mobile","kmm"] },
  { canonical: "MAUI Blazor", family: "mobile", stackDefining: false, aliases: ["maui blazor","blazor hybrid","blazor maui",".net maui blazor"] },
  { canonical: "Objective-C", family: "mobile", stackDefining: true, aliases: ["objective-c","objective c","objectivec","obj-c","objc"] },
  { canonical: "React Native", family: "mobile", stackDefining: true, aliases: ["react native","react-native","reactnative"] },
  { canonical: "Swift", family: "mobile", stackDefining: true, aliases: ["swift","swift lang","swift language","apple swift"] },
  { canonical: "SwiftUI", family: "mobile", stackDefining: true, aliases: ["swiftui","swift ui"] },
  { canonical: "UIKit", family: "mobile", stackDefining: false, aliases: ["uikit","ui kit"] },
  { canonical: "Xamarin", family: "mobile", stackDefining: true, aliases: ["xamarin","xamarin.forms","xamarin forms","xamarin.ios","xamarin.android","xamarin native"] },
  { canonical: "Xcode", family: "mobile", stackDefining: false, aliases: ["xcode"] },
  { canonical: "Blade", family: "php", stackDefining: false, aliases: ["blade templating","laravel blade","blade"] },
  { canonical: "CakePHP", family: "php", stackDefining: true, aliases: ["cakephp","cake php"] },
  { canonical: "CodeIgniter", family: "php", stackDefining: true, aliases: ["codeigniter","code igniter"] },
  { canonical: "Composer", family: "php", stackDefining: false, aliases: ["composer"] },
  { canonical: "Doctrine", family: "php", stackDefining: false, aliases: ["doctrine","doctrine orm"] },
  { canonical: "Eloquent", family: "php", stackDefining: false, aliases: ["eloquent","eloquent orm"] },
  { canonical: "Laminas", family: "php", stackDefining: true, aliases: ["laminas","zend framework","zend"] },
  { canonical: "Laravel", family: "php", stackDefining: true, aliases: ["laravel"] },
  { canonical: "Lumen", family: "php", stackDefining: true, aliases: ["lumen"] },
  { canonical: "Phalcon", family: "php", stackDefining: true, aliases: ["phalcon"] },
  { canonical: "PHP", family: "php", stackDefining: true, aliases: ["php","php7","php 7","php8","php 8","php 8.1","php 8.2"] },
  { canonical: "Slim", family: "php", stackDefining: true, aliases: ["slim framework","slim php","slim"] },
  { canonical: "Symfony", family: "php", stackDefining: true, aliases: ["symfony"] },
  { canonical: "Twig", family: "php", stackDefining: false, aliases: ["twig"] },
  { canonical: "Yii", family: "php", stackDefining: true, aliases: ["yii","yii2","yii framework"] },
  { canonical: "Backtesting", family: "python-data-ml", stackDefining: false, aliases: ["backtesting","back-testing"] },
  { canonical: "CatBoost", family: "python-data-ml", stackDefining: false, aliases: ["catboost","cat boost"] },
  { canonical: "Causal Inference", family: "python-data-ml", stackDefining: false, aliases: ["causal inference","difference-in-differences","diff-in-diff","propensity score"] },
  { canonical: "Chroma", family: "python-data-ml", stackDefining: false, aliases: ["chromadb","chroma db","chroma vector store","chroma"] },
  { canonical: "Computer Vision", family: "python-data-ml", stackDefining: false, aliases: ["computer vision","cv (computer vision)"] },
  { canonical: "Computer Vision", family: "python-data-ml", stackDefining: false, aliases: ["computer vision","image classification","object detection"] },
  { canonical: "Dask", family: "python-data-ml", stackDefining: false, aliases: ["dask"] },
  { canonical: "Data Visualization", family: "python-data-ml", stackDefining: false, aliases: ["data visualization","data visualisation","dashboarding"] },
  { canonical: "Deep Learning", family: "python-data-ml", stackDefining: false, aliases: ["deep learning","deep neural networks","dnn"] },
  { canonical: "Deep Learning", family: "python-data-ml", stackDefining: false, aliases: ["deep learning","neural network","neural networks"] },
  { canonical: "DVC", family: "python-data-ml", stackDefining: false, aliases: ["dvc","data version control"] },
  { canonical: "FAISS", family: "python-data-ml", stackDefining: false, aliases: ["faiss","facebook ai similarity search"] },
  { canonical: "FastAI", family: "python-data-ml", stackDefining: false, aliases: ["fastai","fast.ai","fast ai"] },
  { canonical: "Feature Engineering", family: "python-data-ml", stackDefining: false, aliases: ["feature engineering"] },
  { canonical: "Gensim", family: "python-data-ml", stackDefining: false, aliases: ["gensim"] },
  { canonical: "Hugging Face Datasets", family: "python-data-ml", stackDefining: false, aliases: ["hugging face datasets","huggingface datasets","datasets library"] },
  { canonical: "Hugging Face Transformers", family: "python-data-ml", stackDefining: true, aliases: ["hugging face transformers","huggingface transformers","hugging face","huggingface","transformers library","hf transformers"] },
  { canonical: "Hypothesis Testing", family: "python-data-ml", stackDefining: false, aliases: ["hypothesis testing","statistical testing","a/b testing","ab testing"] },
  { canonical: "JAX", family: "python-data-ml", stackDefining: false, aliases: ["jax library","google jax","jax/flax","jax"] },
  { canonical: "Jupyter", family: "python-data-ml", stackDefining: false, aliases: ["jupyter","jupyter notebook","jupyterlab","jupyter lab","ipython notebook"] },
  { canonical: "Keras", family: "python-data-ml", stackDefining: false, aliases: ["keras","tf.keras"] },
  { canonical: "LangChain", family: "python-data-ml", stackDefining: true, aliases: ["langchain","lang chain","langchainjs"] },
  { canonical: "LightGBM", family: "python-data-ml", stackDefining: false, aliases: ["lightgbm","light gbm","lgbm","lgb"] },
  { canonical: "LlamaIndex", family: "python-data-ml", stackDefining: false, aliases: ["llamaindex","llama index","llama-index","gpt index"] },
  { canonical: "LLM", family: "python-data-ml", stackDefining: false, aliases: ["llm","llms","large language model","large language models","large-language-model"] },
  { canonical: "Machine Learning", family: "python-data-ml", stackDefining: false, aliases: ["machine learning","ml (machine learning)"] },
  { canonical: "Machine Learning", family: "python-data-ml", stackDefining: false, aliases: ["machine learning"] },
  { canonical: "Matplotlib", family: "python-data-ml", stackDefining: false, aliases: ["matplotlib","pyplot","matplotlib.pyplot"] },
  { canonical: "MLflow", family: "python-data-ml", stackDefining: false, aliases: ["mlflow","ml flow","ml-flow"] },
  { canonical: "MLOps", family: "python-data-ml", stackDefining: false, aliases: ["mlops","ml ops","model deployment","model serving"] },
  { canonical: "Monte Carlo", family: "python-data-ml", stackDefining: false, aliases: ["monte carlo","monte-carlo"] },
  { canonical: "Natural Language Processing", family: "python-data-ml", stackDefining: false, aliases: ["nlp","natural language processing","named entity recognition"] },
  { canonical: "NLP", family: "python-data-ml", stackDefining: false, aliases: ["nlp","natural language processing"] },
  { canonical: "NLTK", family: "python-data-ml", stackDefining: false, aliases: ["nltk","natural language toolkit"] },
  { canonical: "NumPy", family: "python-data-ml", stackDefining: false, aliases: ["numpy","np.array","numerical python"] },
  { canonical: "ONNX", family: "python-data-ml", stackDefining: false, aliases: ["onnx","onnx runtime","onnxruntime","open neural network exchange"] },
  { canonical: "OpenAI API", family: "python-data-ml", stackDefining: false, aliases: ["openai api","openai python","openai sdk","gpt-4 api","gpt api"] },
  { canonical: "OpenCV", family: "python-data-ml", stackDefining: false, aliases: ["opencv","open cv","cv2","opencv-python"] },
  { canonical: "Optuna", family: "python-data-ml", stackDefining: false, aliases: ["optuna"] },
  { canonical: "pandas", family: "python-data-ml", stackDefining: true, aliases: ["pandas","pandas dataframe","pd.dataframe"] },
  { canonical: "Pinecone", family: "python-data-ml", stackDefining: false, aliases: ["pinecone","pinecone vector database"] },
  { canonical: "Plotly", family: "python-data-ml", stackDefining: false, aliases: ["plotly","plotly dash"] },
  { canonical: "Polars", family: "python-data-ml", stackDefining: false, aliases: ["polars","polars dataframe"] },
  { canonical: "PySpark", family: "python-data-ml", stackDefining: false, aliases: ["pyspark","py-spark","spark python api"] },
  { canonical: "PyTorch", family: "python-data-ml", stackDefining: true, aliases: ["pytorch","py-torch","torch","libtorch"] },
  { canonical: "PyTorch Lightning", family: "python-data-ml", stackDefining: false, aliases: ["pytorch lightning","pytorch-lightning","lightning ai"] },
  { canonical: "Quantitative Finance", family: "python-data-ml", stackDefining: false, aliases: ["quantitative finance","derivatives pricing","option pricing","value at risk","black-scholes","stochastic calculus"] },
  { canonical: "RAG", family: "python-data-ml", stackDefining: false, aliases: ["rag","retrieval augmented generation","retrieval-augmented generation"] },
  { canonical: "Ray", family: "python-data-ml", stackDefining: false, aliases: ["ray.io","ray tune","ray serve","ray distributed","ray"] },
  { canonical: "Recommender Systems", family: "python-data-ml", stackDefining: false, aliases: ["recommender system","recommendation system","recommender systems"] },
  { canonical: "Reinforcement Learning", family: "python-data-ml", stackDefining: false, aliases: ["reinforcement learning"] },
  { canonical: "scikit-learn", family: "python-data-ml", stackDefining: true, aliases: ["scikit-learn","scikit learn","sklearn","sci-kit learn"] },
  { canonical: "SciPy", family: "python-data-ml", stackDefining: false, aliases: ["scipy","sci-py"] },
  { canonical: "Seaborn", family: "python-data-ml", stackDefining: false, aliases: ["seaborn"] },
  { canonical: "spaCy", family: "python-data-ml", stackDefining: false, aliases: ["spacy","spa cy"] },
  { canonical: "statsmodels", family: "python-data-ml", stackDefining: false, aliases: ["statsmodels","stats models"] },
  { canonical: "TensorFlow", family: "python-data-ml", stackDefining: true, aliases: ["tensorflow","tensor flow","tf.keras","tflite"] },
  { canonical: "Time-Series Forecasting", family: "python-data-ml", stackDefining: false, aliases: ["time series","time-series","forecasting","arima","sarimax"] },
  { canonical: "Weights & Biases", family: "python-data-ml", stackDefining: false, aliases: ["weights & biases","weights and biases","wandb","w&b"] },
  { canonical: "XGBoost", family: "python-data-ml", stackDefining: false, aliases: ["xgboost","xg-boost","extreme gradient boosting"] },
  { canonical: "aiohttp", family: "python-web", stackDefining: true, aliases: ["aiohttp","aio-http"] },
  { canonical: "Alembic", family: "python-web", stackDefining: false, aliases: ["alembic","alembic migrations"] },
  { canonical: "ASGI", family: "python-web", stackDefining: false, aliases: ["asgi","asgi server"] },
  { canonical: "asyncio", family: "python-web", stackDefining: false, aliases: ["asyncio","async io python","async await python"] },
  { canonical: "Bottle", family: "python-web", stackDefining: true, aliases: ["bottle.py","bottle framework","bottlepy","bottle"] },
  { canonical: "Celery", family: "python-web", stackDefining: false, aliases: ["celery","celery beat","celery worker"] },
  { canonical: "Conda", family: "python-web", stackDefining: false, aliases: ["conda","anaconda","miniconda"] },
  { canonical: "Django", family: "python-web", stackDefining: true, aliases: ["django","django framework"] },
  { canonical: "Django Channels", family: "python-web", stackDefining: false, aliases: ["django channels","channels websockets"] },
  { canonical: "Django Channels/WebSockets", family: "python-web", stackDefining: false, aliases: ["websockets python","python websockets","django channels/websockets"] },
  { canonical: "Django ORM", family: "python-web", stackDefining: false, aliases: ["django orm","django models"] },
  { canonical: "Django REST Framework", family: "python-web", stackDefining: true, aliases: ["django rest framework","djangorestframework","drf","django-rest-framework","django rest"] },
  { canonical: "Falcon", family: "python-web", stackDefining: true, aliases: ["falcon framework","falconframework","falcon"] },
  { canonical: "FastAPI", family: "python-web", stackDefining: true, aliases: ["fastapi","fast api","fast-api"] },
  { canonical: "Flask", family: "python-web", stackDefining: true, aliases: ["flask"] },
  { canonical: "Flask-RESTful", family: "python-web", stackDefining: false, aliases: ["flask-restful","flask restful","flask-restx","flask restx"] },
  { canonical: "GraphQL (Graphene)", family: "python-web", stackDefining: false, aliases: ["graphene","graphene-python","graphene python","strawberry graphql","ariadne","graphql (graphene)"] },
  { canonical: "Gunicorn", family: "python-web", stackDefining: false, aliases: ["gunicorn","green unicorn"] },
  { canonical: "Jinja", family: "python-web", stackDefining: false, aliases: ["jinja","jinja2","jinja 2","jinja templates","jinja templating"] },
  { canonical: "Marshmallow", family: "python-web", stackDefining: false, aliases: ["marshmallow","marshmallow schema"] },
  { canonical: "Peewee", family: "python-web", stackDefining: false, aliases: ["peewee","peewee orm"] },
  { canonical: "pip", family: "python-web", stackDefining: false, aliases: ["pip","pip install","python pip"] },
  { canonical: "Poetry", family: "python-web", stackDefining: false, aliases: ["python poetry","poetry packaging","poetry"] },
  { canonical: "Pydantic", family: "python-web", stackDefining: false, aliases: ["pydantic"] },
  { canonical: "Pyramid", family: "python-web", stackDefining: true, aliases: ["pyramid","pyramid framework","pylons pyramid"] },
  { canonical: "Python", family: "python-web", stackDefining: true, aliases: ["python","python3","python 3","cpython"] },
  { canonical: "Sanic", family: "python-web", stackDefining: true, aliases: ["sanic"] },
  { canonical: "SQLAlchemy", family: "python-web", stackDefining: false, aliases: ["sqlalchemy","sql alchemy","sqlalchemy orm"] },
  { canonical: "Starlette", family: "python-web", stackDefining: true, aliases: ["starlette"] },
  { canonical: "Tornado", family: "python-web", stackDefining: true, aliases: ["tornado","tornado web"] },
  { canonical: "Tornado/Twisted", family: "python-web", stackDefining: true, aliases: ["twisted","twisted matrix","twisted python","tornado/twisted"] },
  { canonical: "Tortoise ORM", family: "python-web", stackDefining: false, aliases: ["tortoise orm","tortoise-orm"] },
  { canonical: "Uvicorn", family: "python-web", stackDefining: false, aliases: ["uvicorn"] },
  { canonical: "uWSGI", family: "python-web", stackDefining: false, aliases: ["uwsgi","u wsgi"] },
  { canonical: "WSGI", family: "python-web", stackDefining: false, aliases: ["wsgi","wsgi server"] },
  { canonical: "ActiveRecord", family: "ruby", stackDefining: false, aliases: ["activerecord","active record"] },
  { canonical: "Capistrano", family: "ruby", stackDefining: false, aliases: ["capistrano"] },
  { canonical: "Hanami", family: "ruby", stackDefining: true, aliases: ["hanami"] },
  { canonical: "Hotwire", family: "ruby", stackDefining: false, aliases: ["hotwire","turbo rails","stimulus.js","stimulusjs"] },
  { canonical: "Ruby", family: "ruby", stackDefining: true, aliases: ["ruby","ruby lang"] },
  { canonical: "Ruby on Rails", family: "ruby", stackDefining: true, aliases: ["ruby on rails","rails","ror","rails framework"] },
  { canonical: "Sidekiq", family: "ruby", stackDefining: false, aliases: ["sidekiq"] },
  { canonical: "Sinatra", family: "ruby", stackDefining: true, aliases: ["sinatra"] },
  { canonical: "Actix", family: "rust", stackDefining: true, aliases: ["actix","actix-web","actix web"] },
  { canonical: "Axum", family: "rust", stackDefining: true, aliases: ["axum"] },
  { canonical: "Cargo", family: "rust", stackDefining: false, aliases: ["cargo","rust cargo"] },
  { canonical: "Diesel", family: "rust", stackDefining: false, aliases: ["diesel orm","diesel.rs","diesel"] },
  { canonical: "Rocket", family: "rust", stackDefining: true, aliases: ["rocket framework","rocket.rs","rocket"] },
  { canonical: "Rust", family: "rust", stackDefining: true, aliases: ["rust","rust lang","rustlang"] },
  { canonical: "Serde", family: "rust", stackDefining: false, aliases: ["serde"] },
  { canonical: "Tauri", family: "rust", stackDefining: true, aliases: ["tauri"] },
  { canonical: "Tokio", family: "rust", stackDefining: true, aliases: ["tokio"] },
  { canonical: "Warp", family: "rust", stackDefining: true, aliases: ["warp framework","warp.rs","warp"] },
  { canonical: "AssertJ", family: "testing", stackDefining: false, aliases: ["assertj"] },
  { canonical: "Cucumber", family: "testing", stackDefining: false, aliases: ["cucumber","cucumber-jvm","gherkin"] },
  { canonical: "Cypress", family: "testing", stackDefining: false, aliases: ["cypress","cypress.io"] },
  { canonical: "Hamcrest", family: "testing", stackDefining: false, aliases: ["hamcrest"] },
  { canonical: "Jest", family: "testing", stackDefining: false, aliases: ["jest"] },
  { canonical: "JUnit", family: "testing", stackDefining: false, aliases: ["junit","junit 5","junit5","junit 4","jupiter"] },
  { canonical: "Mockito", family: "testing", stackDefining: false, aliases: ["mockito"] },
  { canonical: "Moq", family: "testing", stackDefining: false, aliases: ["moq","moq framework"] },
  { canonical: "MSTest", family: "testing", stackDefining: false, aliases: ["mstest","ms test","ms-test"] },
  { canonical: "NUnit", family: "testing", stackDefining: false, aliases: ["nunit","n-unit"] },
  { canonical: "Pest", family: "testing", stackDefining: false, aliases: ["pestphp","pest php","pest"] },
  { canonical: "PHPUnit", family: "testing", stackDefining: false, aliases: ["phpunit","php unit"] },
  { canonical: "Playwright", family: "testing", stackDefining: false, aliases: ["playwright"] },
  { canonical: "pytest", family: "testing", stackDefining: false, aliases: ["pytest","py.test","pytest-django","pytest django"] },
  { canonical: "RSpec", family: "testing", stackDefining: false, aliases: ["rspec"] },
  { canonical: "Selenium", family: "testing", stackDefining: false, aliases: ["selenium","selenium webdriver"] },
  { canonical: "Spock", family: "testing", stackDefining: false, aliases: ["spock framework","spock testing","spock"] },
  { canonical: "TestNG", family: "testing", stackDefining: false, aliases: ["testng"] },
  { canonical: "unittest", family: "testing", stackDefining: false, aliases: ["unittest","python unittest","pyunit"] },
  { canonical: "xUnit", family: "testing", stackDefining: false, aliases: ["xunit","xunit.net","x-unit"] },
];

// English words / short tokens that are ALSO real skill aliases (go, spring, swift, echo,
// less, play, c, r, …). These match ONLY when the line carries a tech anchor (another
// recognized skill or a context word like developer/framework/backend), so prose like
// "we will go to market in spring" never registers as Go + Spring.
export const AMBIGUOUS = new Set(["ant","axum","bun","c","chai","crystal","dart","echo","expo","fiber","gin","go","hapi","jest","koa","less","mocha","next","nim","play","qt","r","remix","rocket","rust","sass","scss","slim","spring","swift","warp"]);
