import { NextResponse } from 'next/server';
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import yaml from 'js-yaml';
import { gateMutation, isPublicMode } from '@/lib/gate';
import { repoRoot } from '@/lib/repo';
import { bad, readJson } from '@/lib/http';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// POST /api/onboard/confirm { profile: {...}, parsedText: "..." }
// Write data/profile.yml and data/cv.master.md from wizard form data.
// This is the web-native replacement for `/cos onboard` in Claude Code.
// No LLM involved: profile comes from user's form, master CV is parsed text.
// Guardrail honored: nothing is fabricated — profile = user-filled fields,
// master = exact text extracted from their own CV files.
export async function POST(request: Request) {
  if (isPublicMode()) return NextResponse.json({ ok: false, error: 'write runs on your local instance' }, { status: 403 });
  const gate = gateMutation();
  if (gate) return gate;

  const body = await readJson(request);
  const fields = (body.profile || {}) as ProfileFields;
  const parsedText = typeof body.parsedText === 'string' ? body.parsedText.trim() : '';

  if (!fields.full_name?.trim()) return bad('full_name is required');
  if (!parsedText) return bad('parsedText is required — upload and parse your CV first');

  const root = repoRoot();
  const dataDir = join(root, 'data');
  await mkdir(dataDir, { recursive: true });

  // Build profile object
  const targetRoles = parseLines(fields.target_roles_raw);
  const profileObj = buildProfileObject(fields, targetRoles);
  const profileYaml = [
    `# CareerOS master profile — ${fields.full_name}`,
    `# Generated by the web wizard on ${new Date().toISOString().slice(0, 10)}.`,
    `# Review and edit this file directly to tune CareerOS to you.`,
    `# Run /cos patterns in Claude Code to customise scoring + archetypes.`,
    ``,
    yaml.dump(profileObj, { lineWidth: 120, quotingType: '"', noRefs: true }),
  ].join('\n');

  // Write profile.yml and cv.master.md
  await writeFile(join(dataDir, 'profile.yml'), profileYaml, 'utf8');
  await writeFile(join(dataDir, 'cv.master.md'), parsedText, 'utf8');

  return NextResponse.json({ ok: true, message: 'Profile saved. CareerOS is ready.' });
}

interface ProfileFields {
  full_name?: string;
  email?: string;
  phone?: string;
  location?: string;
  country?: string;
  city?: string;
  linkedin?: string;
  github?: string;
  portfolio_url?: string;
  target_roles_raw?: string;   // newline-separated job titles
  visa_status?: string;
  comp_target?: string;
  comp_min?: string;
  comp_currency?: string;
  location_flexibility?: string;
  cv_template?: string;
}

function parseLines(raw = ''): string[] {
  return raw.split('\n').map((l) => l.trim()).filter(Boolean);
}

function buildProfileObject(f: ProfileFields, targetRoles: string[]) {
  return {
    candidate: {
      full_name: f.full_name || '',
      email: f.email || '',
      phone: f.phone || '',
      location: f.location || '',
      linkedin: f.linkedin || '',
      portfolio_url: f.portfolio_url || '',
      github: f.github || '',
    },
    target_roles: {
      primary: targetRoles,
      archetypes: [],  // filled by /cos patterns or learning loop
    },
    narrative: {
      headline: '',    // fill via /cos recalibrate-voice or edit manually
      exit_story: '',
      superpowers: [],
      proof_points: [],
      voice: {
        tone: 'direct, concrete; lets metrics and tools do the talking',
        sentence_length: 'short-to-medium',
        signature_phrases: [],
        avoid: ['passionate about', 'results-driven', 'synergy'],
      },
    },
    compensation: {
      target_range: f.comp_target || '',
      currency: f.comp_currency || 'USD',
      minimum: f.comp_min || '',
      location_flexibility: f.location_flexibility || '',
    },
    location: {
      country: f.country || '',
      city: f.city || '',
      timezone: guessTimezone(f.country || ''),
      visa_status: f.visa_status || '',
      onsite_availability: '',
    },
    cv: {
      template: f.cv_template || 'classic',
    },
  };
}

function guessTimezone(country: string): string {
  const TZ: Record<string, string> = {
    'usa': 'America/New_York', 'us': 'America/New_York', 'united states': 'America/New_York',
    'uk': 'Europe/London', 'gb': 'Europe/London', 'united kingdom': 'Europe/London',
    'germany': 'Europe/Berlin', 'france': 'Europe/Paris', 'luxembourg': 'Europe/Luxembourg',
    'netherlands': 'Europe/Amsterdam', 'spain': 'Europe/Madrid', 'italy': 'Europe/Rome',
    'india': 'Asia/Kolkata', 'canada': 'America/Toronto', 'australia': 'Australia/Sydney',
    'singapore': 'Asia/Singapore', 'japan': 'Asia/Tokyo', 'uae': 'Asia/Dubai',
  };
  return TZ[country.toLowerCase()] || '';
}
